openapi: 3.0.0
info:
  title: Food Delivery App API
  version: 1.0.0
paths:
  /calculate-price:
    post:
      summary: Calculate delivery price
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                organization_id:
                  type: string
                total_distance:
                  type: integer
                item_type:
                  type: string
                  enum: [perishable, non-perishable]
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
        "404":
          description: Pricing not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
